### ISSUE TITLE
Multiple channel mappings using snowflakes throws NumberFormatException on config save

### ISSUE THREAD

**Issue by zachbr** [zachbr/Dis4IRC#19]
```
16:06:40.330 [main] ERROR init - Could not save configuration file!
java.io.IOException: java.lang.NumberFormatException: For input string: "508562150651068416"
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:174)
	at io.zachbr.dis4irc.config.Configuration.saveConfig$Dis4IRC_main(Configuration.kt:63)
	at io.zachbr.dis4irc.Dis4IRC.<init>(Dis4IRC.kt:76)
	at io.zachbr.dis4irc.Dis4IRCKt.main(Dis4IRC.kt:24)
Caused by: java.lang.NumberFormatException: For input string: "508562150651068416"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.typesafe.config.impl.SimpleConfigObject$RenderComparator.compare(SimpleConfigObject.java:452)
	at com.typesafe.config.impl.SimpleConfigObject$RenderComparator.compare(SimpleConfigObject.java:422)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.typesafe.config.impl.SimpleConfigObject.render(SimpleConfigObject.java:483)
	at com.typesafe.config.impl.AbstractConfigValue.render(AbstractConfigValue.java:356)
	at com.typesafe.config.impl.SimpleConfigObject.render(SimpleConfigObject.java:510)
	at com.typesafe.config.impl.AbstractConfigValue.render(AbstractConfigValue.java:356)
	at com.typesafe.config.impl.SimpleConfigObject.render(SimpleConfigObject.java:510)
	at com.typesafe.config.impl.AbstractConfigValue.render(AbstractConfigValue.java:356)
	at com.typesafe.config.impl.SimpleConfigObject.render(SimpleConfigObject.java:510)
	at com.typesafe.config.impl.AbstractConfigValue.render(AbstractConfigValue.java:356)
	at com.typesafe.config.impl.AbstractConfigValue.render(AbstractConfigValue.java:372)
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.saveInternal(HoconConfigurationLoader.java:219)
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:169)
	... 3 more
```

Caused by:
https://github.com/lightbend/config/issues/604
https://github.com/lightbend/config/issues/541

**Comment by zachbr** [comment]
Will likely just disable the post-bridge initialization configuration save until this is fixed.
As a result, mutator configs will not be saved in the default configuration but people can copy from the example config until this issue is resolved by the HOCON library.

**Comment by zachbr** [comment]
Release 1.0.2 will not save the config after bridge init as a workaround for this issue.

**Comment by zachbr** [comment]
Resolved by library updates at some point, seems to save just fine. Looks like they fixed the sorting system.
