### ISSUE TITLE
IRC -> dumcord messages fail to send due to dumcord API

### ISSUE THREAD

**Issue by RoboMWM** [zachbr/Dis4IRC#26]
Is there a way to have it log to a file? My screen got messed up when I was copying in putty somehow so I took screenshots before I had to end up zapping it with commands outside of it.

![](https://i.imgur.com/r5TR8Py.png)

![](https://i.imgur.com/HD06AzJ.png)

It did this for two consecutive messages, the last messages before that were sent (from IRC) a few minutes ago. If my screen didn't get screwed up I would've seen if it could resolve itself. But yea logging to a file would be good unless there's a way to pipe to file and console.

**Comment by RoboMWM** [comment]
One thing to note is that this bot is currently hosted on an Azure instance and if keepalives aren't being sent, a TCP connection will be dropped - at least I've noticed I had to configure ssh to send keepalives to keep my sessions alive when idle.

**Comment by RoboMWM** [comment]
Running 6eb61c

**Comment by zachbr** [comment]
```java -jar dis4irc-xxx.jar 2>&1 | tee file-out.txt``` will output to both places otherwise you could use a log4j config but I run it through systemd anyway so I never added it to the default config.

**Comment by RoboMWM** [comment]
Doesn't work when I run `screen -S bridge java -jar Dis4IRC-1.0.3-SNAPSHOT.jar 2>&1 | tee file-out.txt` from a bash script (file is created but nothing is piped to it) since I'm a noob at bash stuff so for now I just create the screen manually and run the bridge. Issue happened twice several hours ago during activity, though the other times it happened (with 1.0.2 at least) were during low activity. All the same though with discord API timing out and stuff. Anyways, will now be able to get a proper log for next time, thanks.

**Comment by jamierocks** [comment]
Probably needs to be `screen -S bridge "java -jar Dis4IRC-1.0.3-SNAPSHOT.jar 2>&1 | tee file-out.txt"` - else it would pipe the screen command I think.

**Comment by RoboMWM** [comment]
So I haven't had a time yet recently where I have both dumcord and IRC open, but I decided to take a look in the log and see if I could find it. And I did find one.

So in this case the two messages that never made it to dumcord from IRC were:
> RoboMWM: spigot signature
> RoboMWM: idk if I put it in about

The last message in this snippet from IRC ("where's ur arenas") did make it though.

```
[02:24:04] [default] [DEBUG] - IRC MSG #griefprevention RoboMWM: hmm I could, make a request on the request thread
[02:24:04] [default] [DEBUG] - Message from #griefprevention RoboMWM took 0ms to handle
[02:24:04] [net.dv8tion.jda.core.requests.Requester] [DEBUG] - Received response with following cf-rays: [4c0f582e4dd85170-SJC]
[02:24:13] [default] [DEBUG] - DISCORD MSG griefprevention iZeusi: Where abouts is that bud?
[02:24:13] [default] [DEBUG] - Message from griefprevention iZeusi took 0ms to handle
[02:28:46] [default] [DEBUG] - IRC MSG #griefprevention RoboMWM: spigot signature
[02:28:46] [default] [DEBUG] - Message from #griefprevention RoboMWM took 0ms to handle
[02:28:50] [default] [DEBUG] - IRC MSG #griefprevention RoboMWM: idk if I put it in about
[02:28:50] [default] [DEBUG] - Message from #griefprevention RoboMWM took 0ms to handle
[02:29:06] [net.dv8tion.jda.core.requests.Requester] [ERROR] - Requester timed out while executing a request
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:655) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:663) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:137) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:101) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:191) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:234) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[02:29:06] [net.dv8tion.jda.core.requests.RestAction] [ERROR] - RestAction queue returned failure
net.dv8tion.jda.core.exceptions.ErrorResponseException: -1: java.net.SocketTimeoutException
	at net.dv8tion.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:150) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:96) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.restaction.MessageAction.handleResponse(MessageAction.java:689) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:184) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:236) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:234) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:844) ~[?:?]
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:655) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:663) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:137) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:101) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:191) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	... 10 more
[02:29:26] [net.dv8tion.jda.core.requests.Requester] [ERROR] - Requester timed out while executing a request
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:655) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:663) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:137) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:101) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:191) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:234) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350) [Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[02:29:26] [net.dv8tion.jda.core.requests.RestAction] [ERROR] - RestAction queue returned failure
net.dv8tion.jda.core.exceptions.ErrorResponseException: -1: java.net.SocketTimeoutException
	at net.dv8tion.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:150) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:96) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.restaction.MessageAction.handleResponse(MessageAction.java:689) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:184) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:236) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:234) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:844) ~[?:?]
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:655) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:663) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:137) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:101) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:93) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:191) ~[Dis4IRC-1.0.3-SNAPSHOT.jar:?]
	... 10 more
[02:41:03] [default] [DEBUG] - IRC MSG #MLG RoboMWM: @jenmas where's ur arenas
[02:41:03] [default] [DEBUG] - Message from #MLG RoboMWM took 0ms to handle
```

**Comment by RoboMWM** [comment]
Config for reference. I'm not using any webhooks.

```hocon
# Dis4IRC Configuration File

# A list of bridges that Dis4IRC should start up
# Each bridge can bridge multiple channels between a single IRC and Discord Server
bridges {
    # A bridge is a single bridged connection operating in its own space away from all the other bridges
    # Most people will only need this one default bridge
    default {
        announce-joins-and-quits=false
        # Mappings are the channel <-> channel bridging configurations
        channel-mappings {
            "341448913200349203"="#MLG"
            "420114396313026560"="#griefprevention"
            "420118648418467840"="#robomwm"
            "341451241521545218"="#techfortress"
        }
        # Your discord API key you registered your bot with
        discord-api-key="REDACTED"
        # Configuration for connecting to the IRC server
        irc {
            allow-invalid-ssl-certs=false
            anti-ping=true
            # A list of __raw__ irc messages to send
           init-commands-list=[
                "PRIVMSG NICKSERV info",
                "PRIVMSG NICKSERV help"
            ]
            nickname=Dumcord
            # Messages that match this regular expression will be passed to IRC without a user prefix
            no-prefix-regex=null
            port="6697"
            realname=dum
            server="irc.spi.gt"
            use-ssl=true
            username=cord
        }
    }
}
debug-logging=true
```

**Comment by zachbr** [comment]
That's just Discord API being garbage. Or your connection to it I suppose. I suppose we can investigate adding some system for making sure messages send and attempting to resend if they fail.

**Comment by RoboMWM** [comment]
@jamierocks just tried that now, and that doesn't work because it tries to execute a file that's named as such in the doublequotes.
