### ISSUE TITLE
IRC connection constantly being closed with null reason

### ISSUE THREAD

**Issue by RoboMWM** [zachbr/Dis4IRC#31]
Unfortunately I restarted it before moving the log output so I don't have that anymore, but it was disconnected from both spigot and esper.

```
[21:31:03] [esper] [WARN] - IRC connection closed: null reason
[21:31:03] [esper] [INFO] - Will attempt to reconnect
[21:31:06] [io.netty.handler.ssl.SslHandler] [DEBUG] - [id: 0x03115712, L:/redacted:53213 - R:irc.esper.net/45.79.137.210:6697] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[21:31:44] [esper] [WARN] - IRC connection closed: null reason
[21:31:44] [esper] [INFO] - Will attempt to reconnect
[21:31:48] [io.netty.handler.ssl.SslHandler] [DEBUG] - [id: 0x944541c1, L:/redacted:48874 - R:irc.esper.net/139.99.136.176:6697] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[21:32:26] [esper] [WARN] - IRC connection closed: null reason
[21:32:26] [esper] [INFO] - Will attempt to reconnect
[21:32:30] [io.netty.handler.ssl.SslHandler] [DEBUG] - [id: 0xcaed116e, L:/redacted:49585 - R:irc.esper.net/185.52.1.101:6697] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
```

**Comment by zachbr** [comment]
I think the first priority is going to be sorting out why its getting a null reason. It's not a very useful message without it.

**Comment by Zarthus** [comment]
I encountered the same after a ping timeout, on the latest of #35 (with cherry picked 34)

```
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 4552524f52203a5265636f6e6e656374696e6720746f6f20666173742c207468726f74746c65642e0d0a
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1178)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        ... 16 more
[16:23:52] [esper] [WARN] - IRC connection closed: null reason
[16:23:52] [esper] [INFO] - Will attempt to reconnect
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 4552524f52203a5265636f6e6e656374696e6720746f6f20666173742c207468726f74746c65642e0d0a
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 4552524f52203a5265636f6e6e656374696e6720746f6f20666173742c207468726f74746c65642e0d0a
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1178)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        ... 16 more
[16:24:44] [esper] [WARN] - IRC connection closed: null reason
[16:24:44] [esper] [INFO] - Will attempt to reconnect
[16:25:24] [esper] [WARN] - IRC connection closed: null reason
[16:25:24] [esper] [INFO] - Will attempt to reconnect
[16:26:09] [esper] [WARN] - IRC connection closed: null reason
[16:26:09] [esper] [INFO] - Will attempt to reconnect
[16:27:03] [esper] [WARN] - IRC connection closed: null reason
[16:27:03] [esper] [INFO] - Will attempt to reconnect
[16:27:57] [esper] [WARN] - IRC connection closed: null reason
[16:27:57] [esper] [INFO] - Will attempt to reconnect
[16:28:51] [esper] [WARN] - IRC connection closed: null reason
[16:28:51] [esper] [INFO] - Will attempt to reconnect
[16:29:45] [esper] [WARN] - IRC connection closed: null reason
[16:29:45] [esper] [INFO] - Will attempt to reconnect
[16:30:33] [esper] [WARN] - IRC connection closed: null reason
[16:30:33] [esper] [INFO] - Will attempt to reconnect
[16:31:26] [esper] [WARN] - IRC connection closed: null reason
[16:31:26] [esper] [INFO] - Will attempt to reconnect
[16:32:24] [esper] [WARN] - IRC connection closed: null reason
```

**Comment by RoboMWM** [comment]
The first time it happened since the bridge started there was no stacktrace, but I found a bunch of stacktraces the second time it printed out the "null reason" messages. https://gist.github.com/RoboMWM/5835e71f6c50f0c79b40ce023af76db7

**Comment by RoboMWM** [comment]
I'm guessing it fails to reconnect to IRC if the connection to IRC dies at any time.

**Comment by zachbr** [comment]
Looks like there's a DNS resolver issue on your end from that. It's failing to resolve Spigot IRC, EsperNet, and Discord's API on reconnect.
Is this something you're seeing on just a single server or multiple boxes?

**Comment by RoboMWM** [comment]
Single server - but when it's able to reconnect, it doesn't. I have the full log (several MBs iirc) if needed. Doesn't seem the log posts any private info (bot key, etc.), or is there anything I should scrub out before posting?

**Comment by zachbr** [comment]
There shouldn't be, it intentionally strips sensitive information out, save for chat logs obviously. That being said, you should probably skim it once just in case there's a line I missed or one of the dependencies is logging something sensitive.

**Comment by RoboMWM** [comment]
Well, gist took all 13MB of it. https://gist.github.com/RoboMWM/47779674a636a030291aa17a68643e23

**Comment by zachbr** [comment]
So I'm still not entirely sure why that connection is being closed. Nor am I really sure why your system then fails to resolve the IRC server. I can just tell you that it's doing that.
```
org.kitteh.irc.client.library.exception.KittehConnectionException: java.net.UnknownHostException: irc.spi.gt
	at org.kitteh.irc.client.library.defaults.NettyManager$ClientConnection.lambda$new$0(NettyManager.java:129)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:216)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: irc.spi.gt
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	... 18 more
```

Given that, and that I'm not aware of anyone else with this issue, I'm going to remove this as a blocker from the next release.

**Comment by RoboMWM** [comment]
Not sure either, but it doesn't seem like it's able to recover is the primary issue. I have to restart the bot manually.

**Comment by gedaerm** [comment]
As of now, the problem still persists (in the official download and also when building master).

Once the host loses network for a tiny blip, the bridge won't reconnect.

**Comment by zachbr** [comment]
Thank you for letting me know. I'm going to move your comment to GH-45 and use that as the tracking issue for this.
Things have changed a bit since this ticket was opened.

Please follow that issue for updates, and thanks again for confirmation 👍
