### ISSUE TITLE
javax.security.auth.login.LoginException

### ISSUE THREAD

**Issue by Revul** [zachbr/Dis4IRC#63]
New to all of this, after editing the config and launching it via java -jar Dis4IRC-1.4.2.jar I receive the below error.

Any guidance?

Unable to initialize bridge connections: javax.security.auth.login.LoginException: The provided token is invalid!
javax.security.auth.login.LoginException: The provided token is invalid!
        at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:381)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:301)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:268)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1874)
        at io.zachbr.dis4irc.bridge.pier.discord.DiscordPier.start(DiscordPier.kt:54)
        at io.zachbr.dis4irc.bridge.Bridge.startBridge(Bridge.kt:43)
        at io.zachbr.dis4irc.Dis4IRC.startBridge(Dis4IRC.kt:135)
        at io.zachbr.dis4irc.Dis4IRC.<init>(Dis4IRC.kt:97)
        at io.zachbr.dis4irc.Dis4IRCKt.main(Dis4IRC.kt:36)
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property discordApi has not been initialized
        at io.zachbr.dis4irc.bridge.pier.discord.DiscordPier.onShutdown(DiscordPier.kt:83)
        at io.zachbr.dis4irc.bridge.Bridge.shutdown$Dis4IRC(Bridge.kt:91)
        at io.zachbr.dis4irc.bridge.Bridge.startBridge(Bridge.kt:48)
        at io.zachbr.dis4irc.Dis4IRC.startBridge(Dis4IRC.kt:135)
        at io.zachbr.dis4irc.Dis4IRC.<init>(Dis4IRC.kt:97)
        at io.zachbr.dis4irc.Dis4IRCKt.main(Dis4IRC.kt:36)

**Comment by zachbr** [comment]
Hi,

Discord rejected your API token. This would be the token in your config.hocon that corresponds with 
```hocon
# Your discord API key you registered your bot with
discord-api-key="some-string-of-gibberish-here"
```

This part of the error is Discord rejecting your token:
```
Unable to initialize bridge connections: javax.security.auth.login.LoginException: The provided token is invalid!
javax.security.auth.login.LoginException: The provided token is invalid!
at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:381)
at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:301)
at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:268)
at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1874)
at io.zachbr.dis4irc.bridge.pier.discord.DiscordPier.start(DiscordPier.kt:54)
at io.zachbr.dis4irc.bridge.Bridge.startBridge(Bridge.kt:43)
at io.zachbr.dis4irc.Dis4IRC.startBridge(Dis4IRC.kt:135)
at io.zachbr.dis4irc.Dis4IRC.(Dis4IRC.kt:97)
at io.zachbr.dis4irc.Dis4IRCKt.main(Dis4IRC.kt:36)
```

The second part is just the API library complaining that we tried to shut it down before it started up successfully (will be fixed in the next release but harmless).

You may want to make sure you used a _bot_ token here and not an application key or something else. [Registering A Discord Application](https://github.com/zachbr/Dis4IRC/blob/master/docs/Registering-A-Discord-Application.md) should point you to what you need. Although the screenshots may be just a bit out of date now.

You might also check that there are no extra spaces in between the quotation marks or other characters that have somehow slipped in. The bot API token you put into the config must match exactly what Discord gives you from their developer console. Any extraneous characters at all will make them reject it.

It's hard to say anything in much detail unfortunately, all this really tells me is that the token was rejected by Discord.
